# Site settings
title: Bittercube
email: dev@ocupop.com
description: ''
url: "http://fluent-skunk.cloudvent.net"
permalink: /:title

# Build settings
safe: false
source: src
exclude: ["_assets"]


gems:
  - jekyll-sitemap
  - replace_regex

collections:
  recipes:
    output: true
    layout: recipe
    permalink: /recipes/:name
  bartenders:
    output: true
    layout: bartender
    permalink: /bartenders/:name
  products:
    output: false


store: "https://bittercube.myshopify.com"
products_url: "/admin/products.json?fields=handle,image,title,tags"
facebook:
  title:
  appid:
  description:
  featured_image:
twitter:
  username:
  title:
  featured_image:
  image_alt_text:
  description:


keywords:
  - Citrusy
  - Crisp
  - Refreshing
  - Effervescent
  - Spirit Forward
  - Bitter
  - Smokey
  - Velvetty
  - Tropical
  - Fruity
  - Seasonal
  - Hot
  - Creamy
  - Dry
  - Low ABV
  - Herbaceous
  - Spicy
  - Floral
  - Savory
  - Nutty

