# Site settings
title: Bittercube
email: dev@ocupop.com
description: ''
url: "http://fluent-skunk.cloudvent.net"
permalink: /:title

analytics_code: UA-16640117-2 # accessible via dev@ocupop.com

shop_url: "https://bittercube.myshopify.com"


# Build settings
safe: false
source: src
exclude: ["_assets", "shopify"]


gems:
  - jekyll-sitemap
  - replace_regex
  - jekyll-archives

collections:
  recipes:
    output: true
    layout: recipe
    permalink: /recipes/:name
  syrup_recipes:
    output: false
    layout: syrup_recipe
    permalink: /recipes/syrup/:name
  bartenders:
    output: true
    layout: bartender
    permalink: /bartenders/:name
  products:
    output: false


store: "https://bittercube.myshopify.com"
products_url: "/admin/products.json?fields=handle,image,title,tags"
facebook:
  title: "Bittercube Bitters"
  appid: "261325721045749"
  description: "Our Goal is Simple: To make drinks come true."
  featured_image: "/1200.jpg"
twitter:
  username: "bittercube"
  title: "Bittercube Bitters"
  featured_image: "/280.jpg"
  image_alt_text: "Bittercube Bitters"
  description: "Our Goal is Simple: To make drinks come true."


keywords:
  - Citrusy
  - Crisp
  - Refreshing
  - Effervescent
  - Spirit Forward
  - Bitter
  - Smokey
  - Velvetty
  - Tropical
  - Fruity
  - Seasonal
  - Hot
  - Creamy
  - Dry
  - Low ABV
  - Herbaceous
  - Spicy
  - Floral
  - Savory
  - Nutty

# Archives / API
jekyll-archives:
  enabled: []
  layout: 'default'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
