# Site settings
title: Bittercube
email: dev@ocupop.com
description: ''
url: "http://fluent-skunk.cloudvent.net"
permalink: /:title

# Build settings
safe: false
source: src
exclude: ["_assets"]


gems:
  - jekyll-sitemap

collections:
  recipes:
    output: true
  products:
    output: false


store: "https://bittercube.myshopify.com"
products_url: "/admin/products.json?fields=handle,image,title,tags"
facebook:
  title:
  appid:
  description:
  featured_image:
twitter:
  username:
  title:
  featured_image:
  image_alt_text:
  description:
