- name: Cherry Bark Vanilla
  handle: cherry-bark-vanilla
  shop_url: /products/cherry-bark-vanilla
  description: >-
    Woodsy and aromatic, offering lush notes of Indonesian vanilla, fennel and
    cocoa. Cherry Bark Vanilla surpasses ordinary cherry bitters to add
    dimension to old fashioneds, rye whiskey cocktails, and with seltzer as a
    dry soda.
  image: /assets/img/home/cherrybark.svg
- name: Bolivar
  handle: bolivar
  shop_url: /products/bolivar
  description: >-
    Versatile and aromatic, with floral aromas of jasmine, clove and dried
    fruits. Bolivar Bitters collaborate well with champagne, brandy and
    effervescent craft cocktails.
  image: /assets/img/home/bolivar.svg
- name: Blackstrap
  handle: blackstrap
  shop_url: /products/blackstrap
  description: >-
    Combining two kinds of molasses, and three varietals of cinnamon, with
    nutmeg and kola nut, - leaving intense flavors of baking spice and aromas of
    cinnamon on the mind. Suits hot drinks, scotch and egg white cocktails.
  image: /assets/img/home/blackstrap.svg
- name: Orange
  handle: orange
  shop_url: /products/orange
  description: >-
    Bright, caramelized orange character blends with toasted coriander, cardamom
    and caraway. Adds dimension and complexity to your repertoire of orange
    bitters cocktails.
  image: /assets/img/home/orange.svg
- name: Trinity
  handle: trinity
  shop_url: /products/trinity
  description: >-
    Our proprietary blend of Cherry Bark Vanilla, Orange and Bolivar. A well
    rounded, harmonious combination delivering subtle notes of citrus, dried
    fruits, vanilla and oak.
  image: /assets/img/home/trinity.svg
- name: Root Beer
  handle: root-beer
  shop_url: /products/root-beer
  description: >-
    Simultaneously nostalgic and unexpected. These earthy bitters harmoniously
    combine flavors of birch, wintergreen and sarsaparilla with notes of vanilla
    and star anise.
  image: /assets/img/home/rootbeer.svg
- name: Jamaican No. 1
  handle: jamaican-1
  shop_url: /products/jamaican-1
  description: >-
    Encapsulating intense flavors of ginger, clove and black pepper. These
    generously spiced Jamaican bitters take ginger bitters to an entirely new
    level. Experiment with mules, rum, aged tequila and mezcal.
  image: /assets/img/home/jamaican01.svg
- name: Jamaican No. 2
  handle: jamaican-2
  shop_url: /products/jamaican-2
  description: >-
    Lush and tropical - leading with tart notes of hibiscus and grapefruit and
    balanced with ginger and vanilla. Perfect for palomas, daiquiris, and tiki
    cocktails.
  image: /assets/img/home/jamaican02.svg
- name: Chipotle Cacao
  handle: corazon
  shop_url: /products/corazon
  description: >-
    Rich complexity and depth of heat are achieved using six types of chili
    pepper along with coffee, cacao and cubeb berries. Will certainly heighten
    cocktails like margaritas and Oaxacan Old Fashioneds and other cocktails
    utilizing rum, reposado tequila and mezcal.
  image: /assets/img/home/chipotlecacao.svg